export enum MotionStyleType {
  LUXURY = 'LUXURY',
  MINIMAL = 'MINIMAL',
  TECH = 'TECH',
  CYBERPUNK = 'CYBERPUNK',
  CORPORATE = 'CORPORATE',
  SPORTS = 'SPORTS',
  CINEMATIC = 'CINEMATIC',
  PREMIUM = 'PREMIUM',
  ELEGANT = 'ELEGANT',
  DYNAMIC = 'DYNAMIC'
}
